services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn qazaq_it_project.wsgi:application"
    pythonVersion: 3.10
