# Generated by Django 5.2.6 on 2025-09-25 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Курс атауы')),
                ('description', models.TextField(verbose_name='Сипаттамасы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бағасы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Суреті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курстар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Позиция атауы')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('description', models.TextField(verbose_name='Талаптар мен сипаттама')),
                ('job_type', models.CharField(choices=[('Жұмыс', 'Жұмыс'), ('Стажировка', 'Стажировка')], max_length=20, verbose_name='Түрі')),
                ('location', models.CharField(max_length=150, verbose_name='Орналасқан жері')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жұмыс/Стажировка',
                'verbose_name_plural': 'Жұмыс/Стажировкалар',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Өзі туралы')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профильдер',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Сүйікті курс',
                'verbose_name_plural': 'Сүйікті курстар',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
