# Generated by Django 5.2.6 on 2025-09-25 12:23

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Сабақ тақырыбы')),
                ('order', models.PositiveIntegerField(verbose_name='Реттік нөмірі')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сабақтың мазмұны')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube видеосының сілтемесі')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
                'ordering': ['order'],
            },
        ),
    ]
