# Generated by Django 5.2.6 on 2025-09-25 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='purchased_courses', to=settings.AUTH_USER_MODEL, verbose_name='Сатып алғандар'),
        ),
    ]
