# Generated by Django 5.2.6 on 2025-09-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_enrolled_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Серіктес аты')),
                ('logo', models.ImageField(upload_to='partner_logos/', verbose_name='Логотипі')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Сайтқа сілтеме')),
            ],
            options={
                'verbose_name': 'Серіктес',
                'verbose_name_plural': 'Серіктестер',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Оқиға атауы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сипаттамасы')),
                ('event_date', models.DateTimeField(verbose_name='Өтетін уақыты')),
                ('event_type', models.CharField(choices=[('Вебинар', 'Вебинар'), ('Курс басталуы', 'Курс басталуы'), ('Мастер-класс', 'Мастер-класс')], max_length=50, verbose_name='Оқиға түрі')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course', verbose_name='Байланысты курс')),
            ],
            options={
                'verbose_name': 'Оқиға',
                'verbose_name_plural': 'Оқиғалар кестесі',
                'ordering': ['event_date'],
            },
        ),
    ]
