# Generated by Django 5.2.6 on 2025-09-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_scheduleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Қаралым саны'),
        ),
    ]
