# Generated by Django 5.2.6 on 2025-10-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='Үміткердің аты-жөні')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон нөмірі')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Хат (Cover Letter)')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Түйіндеме (Резюме)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job')),
            ],
            options={
                'verbose_name': 'Жұмысқа өтініш',
                'verbose_name_plural': 'Жұмысқа өтініштер',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
